#!/bin/bash

trap "echo 'Stopping and removing container...'" SIGINT

cd discord-minecraft && npm test && cd ..

docker build -t p0rt23/discord-minecraft . &&\
docker run --rm -d --network="elastic" --name="discord-minecraft" -v discord-minecraft-preferences:/preferences p0rt23/discord-minecraft &&\
docker logs -f discord-minecraft | npx bunyan

docker stop discord-minecraft
